name: event_mng_sys
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.3.6
  image_picker: ^1.1.2
  supabase_flutter: ^2.8.4
  flutter_datetime_picker_plus: ^2.2.0
  provider: ^6.1.4
  google_fonts: ^6.1.0
  intl: ^0.20.2
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
